Fix bug in SSIM
photosynthesis-team/piq pull request #213
Opened 2021-01-21 21:04 UTC by zakajd

Closes #209 and #203 

## Proposed Changes

  - Split code for SSIM and MS-SSIM
  - Fix bug (which ocured to to missing average pooling. See https://github.com/scikit-image/scikit-image/issues/5192 for details
  - Rename variables to have a more meaningful 

TODO:
- [ ] Add tests to compare with MATLAB
- [ ] Update table in README

2021-01-22 09:38 UTC, zakajd commented
Ready for review.
Test failed due to duplicate code in `tests/test_ssim.py` and `tests/test_ms_ssim.py`. This will be fixed during test refactoring (#97 )

2021-01-26 09:20 UTC, denproc requested changes
Nice catch with downsampling bug!
Minor comments about the documentation is to be resolved. Others are optional and can be discussed.

2021-01-26 09:20 UTC, denproc commented on piq/ssim.py
>  def _ssim_per_channel_complex(x: torch.Tensor, y: torch.Tensor, kernel: torch.Tensor,
Shouldn't we update the complex-valued SSIM similarly to SSIM?

2021-01-26 09:20 UTC, denproc commented on piq/ssim.py
>                        k2: float = 0.03) -> Union[torch.Tensor, Tuple[torch.Tensor, torch.Tensor]]:
In case of avoiding Unions as much as possible, we should replace it with `List[torch.Tensor]`.

2021-01-27 18:22 UTC, snk4tr commented
Hey guys. Sonar check fails because of code duplication. As far as I can see, all duplications are in tests, which is absolutely fine with me. Let me know if you think different. Otherwise I will modify Sonar rules to ignore duplications in tests

2021-01-27 21:09 UTC, zakajd commented
@snk4tr  disagree.
Let's leave Sonar cloud checks for feature extractors and add proper testing for models instead. At least check that forward call runs without failure.
We can also move new models there (like PieAPP)

2021-01-28 07:48 UTC, snk4tr commented
@denproc what do you think?

2021-01-30 08:41 UTC, snk4tr commented
> @denproc what do you think?

Ok, I see that @denproc liked the idea of not removing feature extractors from the coverage report. Reverted this change.

2021-02-15 16:32 UTC, snk4tr commented
@zakajd are you working on the one? Let's finilize this one. Let me know if you need any help.

2021-02-18 12:54 UTC, zakajd commented
@snk4tr this one can be merged if there is no failing tests. 

I didn't renamed variables in ms-ssim as proposed by Denis because its better to do that in a separate PR (along with some other renamings).

2021-03-01 18:29 UTC, snk4tr commented
@zakajd are you still working on this one or it is ready?

2021-03-01 18:34 UTC, zakajd commented
@snk4tr  it's ready

2021-03-02 15:22 UTC, snk4tr approved these changes
The PR looks good, ready to merge.
@zakajd FYI: it is easier to follow PRs when they are make to solve a single issue. In this case, the PR is both about fixing the bug and refactoring, which confuses things a little. Consider making separate PRs for these two next time. 
P.S. If you did that because of long review time, do not let long processes to break your style 😉

2021-03-02 15:23 UTC, merged