Sphinx-based Documentation
photosynthesis-team/piq pull request #217
Opened 2021-01-27 15:36 UTC by denproc

Closes #179

## Proposed Changes

  - [Documentation](https://piq.readthedocs.io/en/docs-sphinx/index.html) with overview, functional API and classes.
  - Readthedocs autodeployment 
 
Ready for review. @zakajd @snk4tr 

I suggest you to go through the whole documentation to propose any design improvements and docstring changes to be resolved.

2021-01-28 15:06 UTC, snk4tr requested changes

2021-01-28 15:06 UTC, snk4tr commented on docs/source/conf.py
> +project = 'PIQ'
As discussed offline, this change seems to be unnecessary

2021-01-28 15:06 UTC, snk4tr commented on docs/source/index.rst
> +PIQ Documentation
As discussed offline, this change seems to be unnecessary

2021-01-28 15:06 UTC, snk4tr commented on docs/source/index.rst
> +   PIQ (PyTorch Image Quality) is not endorsed by Facebook, Inc.
```suggestion
   PyTorch Image Quality (PIQ) is not endorsed by Facebook, Inc.
```

2021-01-28 15:06 UTC, snk4tr commented on docs/source/index.rst
> +PIQ (PyTorch Image Quality) is a collection of measures and metrics for image quality assessment.
```suggestion
PyTorch Image Quality (PIQ) is a collection of measures and metrics for image quality assessment.
```

2021-01-29 12:25 UTC, denproc commented
@snk4tr @zakajd 
Final version with resolved checkpoints.
Ready for merge

2021-01-29 17:35 UTC, snk4tr approved these changes
Great job, @denproc!

2021-01-29 17:35 UTC, merged