Update documentation
photosynthesis-team/piq pull request #233
Opened 2021-02-10 02:46 UTC by zakajd

Closes #232 

Hi guys.
I completely reworked our documentation and managed to include current README and CONTRIBUTING files into it.
One major update is that I **changed file format** from `Markdown` to `reStructuredText`. If you are not familiar with it,
here is a[ quick tour](https://docutils.sourceforge.io/docs/user/rst/quickref.html#hyperlink-targets).

Reasons to do this:
- It's much more consistent (1 official spec vs. 30+ spec. for different flavours of Markdown)
- It has richer formatting out of the box (simple tables, TOC) and native Sphinx support without extensions
- GitHub renders it's same way as `.md` files, so no change from user experience.

Here is other relevant articles 
- https://www.zverovich.net/2016/06/16/rst-vs-markdown.html
- https://www.ericholscher.com/blog/2016/mar/15/dont-use-markdown-for-technical-docs/

## Proposed Changes
  - Re-write and re-structure `README` and `CONTRIBUTING` files
  - Re-write Sphinx build files
  - Added PIQ logo at the top left instead of text (see screenshot). There is also an option to make it transparent.
  - Added piq logo files 
  - Added fancy interactive search extension used at [readthedocs](https://docs.readthedocs.io/en/stable/)
  - Some other small fixes

## What didn't change
- `benchmark.csv`. We have lot's of open PRs with metrics, will prettify table after last one is merged
-  Functions docstrings and other fixes. There is still lot's of work to be done.  Will do it as a separate PR

<img width="1299" alt="doc_demo" src="https://user-images.githubusercontent.com/15848838/107457196-a8ecf280-6b62-11eb-950b-62b503a8ecdb.png">

2021-02-14 17:48 UTC, denproc requested changes
The documentation is hosted [here](https://piq.readthedocs.io/en/docs-include_markdown/index.html).

## General discussion:
I like to keep the single copy of the text used for GitHub and readthedocs both.
However, I disagree with an approach to reuse the readme/contribution as is. 
    - The project overview as a documentation becomes quite heavy with a lot of info on a single page. See [Jupyter documentation](https://jupyterlab.readthedocs.io/en/latest/index.html) as an example. 
    - The links used in GitHub versions and docs versions are different. The links from GitHub based files should lead to GitHub, while documentation ones should keep used at readthdocs. For example, link to contribution guide.
    - There is no need in “Contribution” in documentation as there is “Contribution guide”. However, this section is needed in GitHub based Readme.
    - Badges are not needed in the documentation.
    - The GitHub README does not show the benchmark table due to wrong relative path.


Possible solution:
Create universal sections of smaller size, which can be reused in README and documentation differently. Set up different cross-reference links for GitHub and readthedocs.

2021-02-14 17:48 UTC, denproc commented on docs/source/_static/benchmark.csv
> +DISTS,0.7077 / 0.5212,0.830 / 0.639,0.8137 / 0.6254,- / -
Fix the "-" adding "\\" or copy-paste previous table.
![Screenshot 2021-02-14 at 20 00 44](https://user-images.githubusercontent.com/22414094/107883330-6bd88580-6eff-11eb-8379-a9506e79e1c8.png)

2021-02-14 17:48 UTC, denproc commented on docs/source/conf.py
> +html_logo = '_static/piq_logo.png'
Option 1 (like it is done by pytorch):
1. Let's use logo with transparent background without "by Photosynthesis Team"
2. Let's use the light-grey or white background of the readthedocs theme.

Option 2:
Use just text

I tried to use different combinations of background/logo, unfortunately none of them were satisfying enough to use. Therefore, I suggest to keep just title of the library.

2021-02-14 17:48 UTC, denproc commented on docs/source/readme.rst
> +.. include:: ../../README.rst
```suggestion
PyTorch Image Quality (PIQ) Documentation
=========================================
.. include:: ../../README.rst
```

2021-02-14 17:48 UTC, denproc commented on README.rst
> +PSNR         -       `Peak Signal-to-Noise Ratio <https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio>`_
Add "\\" before "-" here and for further instances.
```suggestion
PSNR         \-       `Peak Signal-to-Noise Ratio <https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio>`_
```

2021-02-14 17:48 UTC, denproc commented on README.rst
> +  PyTorch, the PyTorch logo and any related marks are trademarks of Facebook, Inc.
The readthedocs does not show it as a note.

2021-02-14 17:48 UTC, denproc commented on README.rst
> +.. contents:: Table of Contents
I suggest to use heading for table go content. It is lost in plain text.
![image](https://user-images.githubusercontent.com/22414094/107883789-181b6b80-6f02-11eb-92a3-5e3cf376eb75.png)

2021-02-14 17:48 UTC, denproc commented on README.rst
> +.. csv-table:: Benchmark results
The default style of the table title looks sad. Let's use separate heading or no heading at all.

2021-02-14 17:48 UTC, denproc commented on README.rst
> +.. image:: https://user-images.githubusercontent.com/22414094/106116361-df8a3c80-6162-11eb-83df-f5838110e614.png
To unify the proposed approach, the local copy of the image from docs/_static folder should be used.

2021-02-14 17:48 UTC, denproc commented on README.rst
> +   :file: docs/source/_static/benchmark.csv
Such reference works for the documentation, but does not for GitHub README.

2021-02-14 17:48 UTC, denproc commented on docs/source/index.rst
> +.. include:: ../../README.rst
```suggestion
.. include:: readme.rst
```

2021-02-14 17:48 UTC, denproc commented on README.rst
> +===========  ======  ==========
The tables with list of metrics should be imported as csv files similarly to benchmark to simplify the reuse in different places.

2021-02-14 17:48 UTC, denproc commented on docs/source/index.rst
> +   readme.rst
```suggestion
   readme.rst
   contributing.rst
```

2021-02-14 17:48 UTC, denproc commented on docs/source/index.rst
>     :hidden:
```suggestion
```

2021-02-14 17:48 UTC, denproc commented on docs/source/index.rst
>     contributing.rst
```suggestion
```

2021-02-14 18:10 UTC, denproc commented on docs/source/conf.py
> +}
Option 1 - light-grey background 
```suggestion
html_theme_options = {
    'logo_only': True,
    'style_nav_header_background': '#FAFAFA',
}
```

2021-02-15 16:31 UTC, snk4tr requested changes
Hi @zakajd. Thanks for the refactoring. I like the idea to make the text universal. However, I see some disadvantages of the approach you chose, most of which are already described by @denproc. 
I would like to additionally emphasise that the table with benchmarks in the README is a great thing and should not be removed for the sake of transferability.

2021-02-18 12:33 UTC, zakajd commented
@denproc  @snk4tr 
I tried to apply all your suggestions, but there are 2 problems
- GitHub doesn't allow `include` or `table` command for a [security reasons](https://github.com/github/markup/issues/172). So it's impossible to split everything into small chunks and import as needed.
- Issues with incorrect links is rooted somewhere in sphinx build process so it's not so easy to change them. 

Here is what was done:
1. Applied one hacky way to include parts of README into docs as described [here](https://muffinresearch.co.uk/selectively-including-parts-readme-rst-in-your-docs/)
2. Moved table from csv into README
3. Re-structered index and overview files to include only necessary parts (as discussed with @denproc)

2021-02-18 20:57 UTC, denproc requested changes
@zakajd great rework, nice catch with including files between particular markers. 
I added high-res logo and structure of the index that I meant during discussion. Feel free to change it in case of any inconveniences.

I assume the only issue is missed link for some metric benchmarks.

2021-02-18 20:57 UTC, denproc commented on README.rst
> +.. _link: eval2019 survey
Insert link here

2021-02-18 21:13 UTC, zakajd commented on README.rst
> +.. _link: eval2019 survey
Done 👍

2021-02-18 21:20 UTC, zakajd commented
There is also 1 code smell due to one commented line in conf.py. Please fix this before merge

2021-02-19 09:45 UTC, denproc approved these changes

2021-02-19 09:59 UTC, denproc approved these changes

2021-02-23 16:40 UTC, merged