Unify the documentation style and referencing
photosynthesis-team/piq pull request #243
Opened 2021-03-30 19:10 UTC by denproc

Closes #242

## Proposed Changes

  - References were changed to plain text
  - The doc strings were unified to single format
  - Fixed typos and missing info

2021-04-01 11:23 UTC, denproc commented
Blocked by #15 #244 #245 #246

2021-04-05 18:48 UTC, denproc commented
The documentation is available [here](https://piq--243.org.readthedocs.build/en/243/).

2021-04-08 07:14 UTC, zakajd requested changes
Nice job!
Please see some comments below

2021-04-08 07:14 UTC, zakajd commented on piq/mdsi.py
> +        The batch of Mean Deviation Similarity Index (MDSI) score reduced accordingly
```suggestion
        Mean Deviation Similarity Index between 2 tensors
```

2021-04-08 07:14 UTC, zakajd commented on piq/ms_ssim.py
> +            Value of MS-SSIM loss to be minimized, i.e. ``1-ms_ssim`` in [0, 1] range. In case of 5D tensor,
```suggestion
            Value of MS-SSIM loss to be minimized, i.e. ``1 - ms_ssim`` in [0, 1] range. In case of 5D tensor,
```

2021-04-08 07:14 UTC, zakajd commented on piq/msid.py
>      def __init__(self, ts: torch.Tensor = torch.logspace(-1, 1, 256), k: int = 5, m: int = 10, niters: int = 100,
Can we remove this `torch.logspace(-1, 1, 256)`  inside the function?
This currently leads to a very long description. 

<img width="760" alt="image" src="https://user-images.githubusercontent.com/15848838/113983011-1f9c2880-9852-11eb-8f7f-d1f5b4af3021.png">

2021-04-08 07:14 UTC, zakajd commented on piq/vsi.py
> +        DOI:`10.1109/TIP.2003.819861`
Thats SSIM paper, not VSI

2021-04-08 07:14 UTC, zakajd commented on piq/vsi.py
> +        DOI:`10.1109/TIP.2003.819861`
Wrong paper

2021-04-08 12:29 UTC, denproc commented
@zakajd done

2021-04-14 10:18 UTC, zakajd approved these changes
LGTM

2021-04-14 10:20 UTC, merged