Layers/Weights Bug in Content Loss
photosynthesis-team/piq pull request #259
Opened 2021-07-27 18:26 UTC by snk4tr

Closes #258

## Proposed Changes

  - Fix bug with layers/weighs length in the ContentLoss (if number of layers > number of weights => extra layers are skipped => wrong results) via addition of an assertion. Now mismatch will cause an error.
  - Add required tests

2021-08-02 16:35 UTC, snk4tr commented
Ready for review. Btw I have no idea why coverage of `gs.py` decreased since I only fixed `perceptual.py` and the corresponding test file.

2021-08-03 10:40 UTC, denproc requested changes
Minor issue with doubled weight transformation to list of tensors. We can keep any one, but we must not forget about check if `w` is a tensor to avoid UserWarning.

2021-08-03 10:40 UTC, denproc commented on piq/perceptual.py
> +        self.weights = [torch.tensor(w) for w in weights]
Duplicate of line 156

2021-08-03 16:25 UTC, snk4tr commented
@denproc ready now.

2021-08-03 17:49 UTC, merged